# Generated by Django 5.2.6 on 2026-04-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_objects', '0008_sitesettings_copyright_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='albums_group_by',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('year', 'Year')], db_default='none', default='none', help_text='If and how albums are grouped in the list albums view.', verbose_name='Albums / group by'),
        ),
    ]
