# Generated by Django 5.2.6 on 2026-05-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_objects', '0009_sitesettings_albums_group_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='photos_group_by',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('year', 'Year'), ('month', 'Month')], db_default='none', default='none', help_text='If and how photos are grouped in the list photos view.', verbose_name='Photos / group by'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='albums_group_by',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('year', 'Year'), ('month', 'Month')], db_default='none', default='none', help_text='If and how albums are grouped in the list albums view.', verbose_name='Albums / group by'),
        ),
    ]
