# Generated by Django 5.2.6 on 2026-05-08 22:59

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Photo = apps.get_model("photo_objects", "Photo")
    for row in Photo.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('photo_objects', '0011_add_photo_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
