# Generated by Django 5.2.6 on 2026-05-08 22:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_objects', '0012_populate_photo_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
