# Generated by Django 5.2.6 on 2026-05-09 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_objects', '0013_set_photo_uuid_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='photos_orphans',
            field=models.PositiveIntegerField(blank=True, default=24, help_text='If the last page has fewer photos than this number, they will be combined into the penultimate page.', verbose_name='Photos / orphans'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photos_page_size',
            field=models.PositiveIntegerField(blank=True, default=96, help_text='Number of photos to display per page in the list photos view.', validators=[django.core.validators.MinValueValidator(8)], verbose_name='Photos / page size'),
        ),
    ]
