# Generated by Django 5.2.6 on 2026-05-24 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_objects', '0014_sitesettings_photos_paging'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('value', models.CharField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._-]+$', 'Tag must only contain alphanumeric characters, dots, underscores and hyphens.')])),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='photo_objects.tag'),
        ),
    ]
