# Generated by Django 5.2.6 on 2026-05-26 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_objects', '0015_photo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='photochangerequest',
            name='tags',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^([a-zA-Z0-9._-]+(\\s*,\\s*)*)*$', 'Tags must only contain alphanumeric characters, dots, underscores and hyphens.')]),
        ),
        migrations.AlterField(
            model_name='photochangerequest',
            name='alt_text',
            field=models.TextField(blank=True),
        ),
    ]
