# Generated by Django 5.2.6 on 2026-07-25 23:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_objects', '0016_photochangerequest_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('title', models.CharField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._-]+$', 'Album key must only contain alphanumeric characters, dots, underscores and hyphens.')])),
                ('visibility', models.CharField(blank=True, choices=[('public', 'Public'), ('hidden', 'Hidden'), ('private', 'Private'), ('', 'Admin')], db_default='private', default='private')),
                ('priority', models.PositiveIntegerField(blank=True, default=0, help_text='Stories are ordered by priority. Higher priority stories are shown first.')),
                ('cover_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='photo_objects.photo')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='photo_objects.photo')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_references', to='photo_objects.story')),
            ],
            options={
                'ordering': ['photo__timestamp'],
            },
        ),
    ]
