# Generated by Django 4.2.7 on 2023-11-17 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True)),
                ('description', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('title', models.CharField(blank=True)),
                ('description', models.CharField(blank=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.album')),
            ],
        ),
    ]
