# Generated by Django 5.0.7 on 2024-08-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('hidden', 'Hidden'), ('private', 'Private')], default='private')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('title', models.CharField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('tiny_base64', models.TextField(blank=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photo_objects.album')),
            ],
        ),
    ]
