# Generated by Django 5.0.7 on 2024-08-13 23:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._-]+$', 'Key must only contain alphanumeric characters, dots, underscores and hyphens.')])),
                ('title', models.CharField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(blank=True, choices=[('public', 'Public'), ('hidden', 'Hidden'), ('private', 'Private')], db_default='private', default='private')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('key', models.CharField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._-]+$', 'Key must only contain alphanumeric characters, dots, underscores and hyphens.')])),
                ('timestamp', models.DateTimeField()),
                ('title', models.CharField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('tiny_base64', models.TextField(blank=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='photo_objects.album')),
            ],
        ),
    ]
