name: Release
on:
  push:
    tags:
    - 'v*'

jobs:
  release-pypi:
    name: Python Package Index
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: pip install build
    - name: Build Python packages
      run: python -m build --sdist --wheel --outdir dist/
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
  release-ghcr:
    name: GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push container image to GitHub Container Registry
        run: |
          docker build . --target front -t front
          docker build . --target back -t api
          for tag in ${{ github.ref_name }} latest; do
            docker tag front ghcr.io/${{ github.repository }}-front:$tag
            docker push ghcr.io/${{ github.repository }}-front:$tag

            docker tag api ghcr.io/${{ github.repository }}-api:$tag
            docker push ghcr.io/${{ github.repository }}-api:$tag
          done
